import './globals.css';
import type { Metadata } from 'next';
import { poppins } from '@/app/utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={poppins.className}
    >
      <body className='bg-[#F8F9FD]'>{children}</body>
    </html>
  );
}
